// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srpxfzpxiqcewtjdpdyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycHhmenB4aXFjZXd0amRwZHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTg1NzIsImV4cCI6MjA1ODU5NDU3Mn0.m-DinVAmHyzfgoX7d_kTx8NBdjeEjNxuujmiU-axLIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);